/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package rfea;

import static javax.swing.JFrame.EXIT_ON_CLOSE;
import java.awt.BorderLayout;
import java.awt.image.BufferedImage;
import java.io.UnsupportedEncodingException;
import java.net.URL;
import java.net.URLDecoder;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;


/**
 *
 * @author mery-pc
 */
public class SeleccionImg extends JFrame{
    private static final long serialVersionUID = 8937119421588637012L;
    private SelectorAreaImagen selector;
    /**
     * Creates new form SeleccionImg
     */
    public SeleccionImg() {
        initComponents();
        initGUI();
    }
    public void Agregar(){
        //setDefaultCloseOperation(DISPOSE);
        setLayout(new BorderLayout());
        selector = new SelectorAreaImagen();
                }
        private void initGUI() {
                        System.out.println("gola: "+rutaDeURL("/test.jpg"));

        setDefaultCloseOperation(EXIT_ON_CLOSE);
        
        setLayout(new BorderLayout());
        selector = new SelectorAreaImagen();
        System.out.println(rutaDeURL("/test.jpg"));
        selector.setImagen(ProcesarImagen.matABfIMg(ProcesarImagen.getImage()));
        add(selector, BorderLayout.CENTER);
        
        selector.addSelectorListener(new SelectorAreaListener() {

            public void areaSeleccionada(BufferedImage imagen) {
                SelectorAreaImagen s = new SelectorAreaImagen(imagen);
                JDialog d = new JDialog(SeleccionImg.this);
               // jScrollPane1.add(d);
                d.add(s);
                d.pack();
                d.setVisible(true);
            }
        });
        setTitle("Demo " + selector.getClass().getName());
        pack();
        setResizable(false);
    }
    public String rutaDe (String recurso){
        String ruta = getClass().getResource(recurso).getPath();
        //System.out.println(ruta);
        try {
            ruta=URLDecoder.decode(ruta, "UTF-8"); //this will replace %20 with spaces
        } catch (UnsupportedEncodingException ex) {
            Logger.getLogger(FrameDemo.class.getName()).log(Level.SEVERE, null, ex);
        }
    return ruta;
    }
           public URL rutaDeURL(String recurso){
        URL ruta = getClass().getResource(recurso);
    return ruta;
    
    }
        
           
    public static void main(String[] args) {
        SwingUtilities.invokeLater(new Runnable() {

            public void run() {
                SeleccionImg frame = new SeleccionImg();
                frame.setVisible(true);
            }
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 406, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 292, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
